# Generated by Django 3.1.4 on 2020-12-17 17:50

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201215_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
