# Generated by Django 3.1.1 on 2020-10-04 12:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201003_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gps_coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
