# Generated by Django 3.1.1 on 2020-10-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0004_auto_20200408_1844'),
        ('user', '0006_auto_20201017_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='friendship.Friend'),
        ),
    ]
