# Generated by Django 3.1.1 on 2020-10-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0004_auto_20200408_1844'),
        ('user', '0007_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='friendship.Friend'),
        ),
    ]
