# Generated by Django 3.1.4 on 2020-12-13 19:44

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201018_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
