# Generated by Django 3.1.4 on 2020-12-13 22:08

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201213_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
