# Generated by Django 3.1.4 on 2020-12-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201213_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='anniversary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='partner_bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='partner_birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='partner_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='partner_profile_photo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='years_together',
        ),
    ]
