# Generated by Django 3.1.4 on 2020-12-15 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20201215_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='members',
            new_name='member_list',
        ),
    ]
